### PR TITLE
Fixed macro-invocation

### PR DESCRIPTION
**Pull request by 4Luke4**
- Fixed `macro-invocation` (hopefully...).
- Fixed `keyword.control.weidu` in `function-declaration`.

### CODE REVIEW

**Comment by 4Luke4** [comment]
@burner1024 

Also, the following two keywords are missing and they're valid both as action commands and patch commands: `LOCAL_SPRINT` / `LOCAL_SET`.

Should I add them to `weidu-tp2-action` or `weidu-tp2-patch`?

**Comment by burner1024** [comment]
Not sure what was the problem in the first place, but I guess you know better.

As for `LOCAL_SPRINT`/`LOCAL_SET`, doesn't really matter, as we color patch and action keywords the same. _Although in fact this is a situation that might benefit from revisiting._

**Comment by 4Luke4** [comment]
> Not sure what was the problem in the first place, but I guess you know better.

Unlike `FUNCTION`s, `MACRO`s don't need `BEGIN` / `STR_VAR` / `INT_VAR` / `RET` / `RET_ARRAY`. For instance: `LAM TEST // That's it...`

Also, in the current version of MLS the commands `LAM`, `LAUNCH_ACTION_MACRO`, `LAUNCH_PATCH_MACRO`, and `LPM` are not highlighted....

**Comment by 4Luke4** [comment]
@burner1024 

Unfortunately, macro-invocation is still broken (see previous screenshot – in particular: `LAM`, `LAUNCH_ACTION_MACRO`, `LAUNCH_PATCH_MACRO`, and `LPM` are not highlighted....

**Comment by burner1024** [comment]
Sorry, I screwed up and the latest commit didn't make it into release. Published an update now.
It would probably be good to automate release flow, but I don't do it often enough to bother.

**Comment by 4Luke4** [comment]
> Sorry, I screwed up and the latest commit didn't make it into release. Published an update now.
> It would probably be good to automate release flow, but I don't do it often enough to bother.

Sadly, it is still not working as it should... Those keywords are not highlighted....

**Comment by burner1024** [comment]
Well, did it work for you in the development version? Or it isn't tested?

**Comment by 4Luke4** [comment]
> Well, did it work for you in the development version? Or it isn't tested?

Yeah, I'm a dummy, I didn't test it enough.... Anyway, it's weird.... As I've already told you, it should be identical to function-declaration apart from `BEGIN` / `INT_VAR` / `STR_VAR` / `RET` / `RET_ARRAY` / `END`...

**Comment by burner1024** [comment]
pushed one more version

**Comment by 4Luke4** [comment]
> As for `LOCAL_SPRINT`/`LOCAL_SET`, doesn't really matter, as we color patch and action keywords the same...

@burner1024 
Forgot to add them in the end... Please add them for the next release...

**Pull request merged**
