### PR TITLE
Update weidu.completion.yml

### PR DESCRIPTION
**Pull request by 4Luke4**
Autocompletion: WeiDU built-in constants.

### CODE REVIEW

**Comment by burner1024** [comment]
The server currently expects some doc string to go with the name...

**Comment by 4Luke4** [comment]
> The server currently expects some doc string to go with the name...

OK, I can easily add the binary notation for those 32 BITs, but what about AREA_CITY, AREA_DAY, AREA_DUNGEON and so fourth?

**Comment by burner1024** [comment]
I think I'll just allow for empty doc. This shouldn't be abused, however.
Do you want to add new constants to [highlighting](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/master/syntaxes/weidu.tmLanguage.yml#L620), too?

**Comment by 4Luke4** [comment]
> Do you want to add new constants to [highlighting](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/master/syntaxes/weidu.tmLanguage.yml#L620), too?

Yes, why not. How can I do that?

**Comment by burner1024** [comment]
I think the format is obvious, isn't it?

**Comment by 4Luke4** [comment]
> I think the format is obvious, isn't it?

OK, done. Please, check if everything is right....

**Comment by burner1024** [comment]
One small issue, quotes should be escaped. If you use VScode to edit yaml, you'll see that highlighting is wrong. I corrected it.

**Comment by 4Luke4** [comment]
> One small issue, quotes should be escaped. If you use VScode to edit yaml, you'll see that highlighting is wrong. I corrected it.

Just out of curiosity, which quotes are you referring to?

**Comment by burner1024** [comment]
Well, I was imprecise. In fact, what breaks yaml is colon "**:**" in value field, so it should be quoted, but then the double quotes inside should be escaped.
Anyway, just add yaml extension to VScode, and it'll show the errors, something like this:
Captura de pantalla de 2019-05-27 10-10-23

**Pull request merged**
