### PR TITLE
WeiDU v247

### PR DESCRIPTION
**Pull request by 4Luke4**
- Added new `WeiDU v247` keywords
- Misc tweaks (notably `WeiDU constants`)

### CODE REVIEW

**Comment by 4Luke4** [comment]
@burner1024 

Am I missing something? Changes [here](https://weidu.org/~thebigg/README-WeiDU-Changes.txt).

**Comment by burner1024** [comment]
You sure that soundset constants are the same across all CRE versions?

**Comment by 4Luke4** [comment]
> You sure that soundset constants are the same across all CRE versions?

According to the `IESDP`, `CRE v2.2` (IWD2) uses different values.
Should I discard those changes?

**Comment by burner1024** [comment]
I'm not sure, does WeiDU actually account for it? Better to ask Wisp, or check source code directly.

**Comment by 4Luke4** [comment]
> I'm not sure, does WeiDU actually account for it? Better to ask Wisp, or check source code directly.

Unless I'm missing something, [source code](https://github.com/WeiDUorg/weidu/blob/796845951679926f5ca57b65ef6b7622cb88add3/src/var.ml#L181) doesn't take into account IWD2 values, so...

**Comment by burner1024** [comment]
ok, there's very few mods for IWD2, so it's of little concern. Thank you.

**Comment by 4Luke4** [comment]
@burner1024 

You're welcome.
When do you plan to release the next update?

**Comment by burner1024** [comment]
Soon as I get new parse feature working.

**Pull request merged**
