### PR TITLE
[WeiDU, .baf files]Added some useful identifiers to Syntax Highlighting

### PR DESCRIPTION
**Pull request by 4Luke4**
So far:
```
GENERAL.ids
GENDER.ids
HAND.ids
STATS.ids
STATE.ids
SPLSTATE.ids
ALIGN.ids
EA.ids
```

### CODE REVIEW

**Comment by burner1024** [comment]
Looks good. Which game is it?
And are you doing the conversion manually?

**Comment by 4Luke4** [comment]
> Looks good. Which game is it?
> And are you doing the conversion manually?

I own the EE games, so I refer to them...

And yes, I'm doing the conversion manually by copying & pasting from NearInfinity.... Are you saying it can be automated?

**Comment by burner1024** [comment]
OK, which EE game? There are several. (I'm just asking for clarity. I used ToB versions to get started).

> And yes, I'm doing the conversion manually by copying & pasting from NearInfinity.... Are you saying it can be automated?

It can, and it should, in fact. (But it'll still entail a lot of copy-paste work).
Refer to the system for Fallout syntax: I converted the original [txt doc](https://github.com/BGforgeNet/sfall/blob/better-docs/artifacts/scripting/sfall%20function%20notes.txt) into [machine readable format](https://github.com/BGforgeNet/sfall/blob/better-docs/artifacts/scripting/functions.yml). From that format, a small python script generates markdown files, and with Jekyll, a nice [doc](https://sfall.bgforge.net/) is generated and published.
And once it's machine readable, it's easy to automate pulling doc updates into MLS. Right now what I have to do to update Fallout/sfall syntax is to run a [script](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/master/scripts/fallout-update.sh).

I think a similar system would benefit both WeiDU and IESDP (as well as MLS, of course). I remember Wisp mentioning that he's been wanting to move from Latex to something more modern/suitable. Don't know about IESDP maintainers.

I can help with scripting, but this still needs:
1. Support from WeiDU/IESDP guys.
2. [community effort](https://forums.bgforge.net/viewtopic.php?f=35&t=140) for transpiling the docs into machine readable format.

I know there's at least [280 people](https://marketplace.visualstudio.com/items?itemName=BGforge.bgforge-mls) using MLS, so with will to do, it can be achieved in a really short time.
If you think it's worth a try, we can pitch it to the doc maintainers, and if they agree, do a roll call on various forums.

**Comment by 4Luke4** [comment]
@burner1024 
I'm taking into account EE games, all of them (those files should be the same across all those games – As far as I know, only the IWD:EE version of `SPLSTATE.ids` is somewhat different with respect to the BG(2):EE one, it contains less entries....)

**Comment by burner1024** [comment]
OK, I didn't know all the IDS were the same.
I'm merging this request for now. If you feel like trying to talk other people into the larger effort, let me know.

**Comment by 4Luke4** [comment]
> OK, I didn't know all the IDS were the same.

Well, I cannot check the original games because I don't own them... Anyway, I don't expect that EE games replaced / edited the original references (you know, backward compatibility and things like that). I think that all those new references have been added _on top_ of the original ones...
Of course, you need to update the `.json` file....

**Comment by burner1024** [comment]
> Of course, you need to update the `.json` file....

Yes, there's a script for that. The power of automation.

**Pull request merged**
