### PR TITLE
Autocompletion: WeiDU patch and action functions (final)

### PR DESCRIPTION
**Pull request by 4Luke4**
This pull request is meant to add all the remaining patch/action functions to Autocompletion.

### CODE REVIEW

**Comment by burner1024** [comment]
These are some long-ass macros...
Can you update your fork to the latest version? Currently it won't run.

I feel a little bit stupid, but I just recently discovered how you can make [multiliine strings without \n's and quoting in yaml](https://github.com/BGforgeNet/sfall/blob/43606c0e8734072c41ed01200598fa12d2333302/artifacts/scripting/functions.yml#L975) - just fyi.

If you want, I can add you to the org, so that you'll be able to use the repo directly. (I'd still ask to avoid committing to master branch, though.)

**Comment by 4Luke4** [comment]
@burner1024 

OK, done. If I'm not mistaken, no macro should be missing now...

**Comment by burner1024** [comment]
ok, I finally found why is it crapping out on me. [BIT records are wrong](https://github.com/4Luke4/vscode-bgforge-mls/blob/9b32ce7fa337dbbe9b91d68f652c267ddf99d377/server/out/weidu.completion.yml#L2854), they list docs as separate items.

**Comment by 4Luke4** [comment]
> ok, I finally found why is it crapping out on me. [BIT records are wrong](https://github.com/4Luke4/vscode-bgforge-mls/blob/9b32ce7fa337dbbe9b91d68f652c267ddf99d377/server/out/weidu.completion.yml#L2854), they list docs as separate items.

Should be fixed now...

**Pull request merged**
