### PR TITLE
[WeiDU] Added IWD:EE symbolic references to spell.ids

### PR DESCRIPTION
**Pull request by 4Luke4**
Added **IWD:EE** spells to Syntax Highlighting.

### CODE REVIEW

**Comment by burner1024** [comment]
Looks good.
It might be better to use a separate stanza for tokens from other games, for ease of maintenance.
On the other hand, if/when IESDP gets converted into machine readable format, it'll become irrelevant anyway...

**Comment by 4Luke4** [comment]
> It might be better to use a separate stanza for tokens from other games, for ease of maintenance.

Do you mean I should put them to the bottom of that list?

**Comment by burner1024** [comment]
Yes. Something like
```
spell-ids-iwdee:
    name: constant.other.baf.weidu
    patterns:
      - match: \b(?i)(CLERIC_CAUSE_LIGHT_WOUNDS)\b
      ...
```

I'm not quite sure yet what's the best way to support multiple games syntaxes, but for now it's probably best to keep the lists separate.

**Comment by 4Luke4** [comment]
> Yes. Something like
> 
> ```
> spell-ids-iwdee:
>     name: constant.other.baf.weidu
>     patterns:
>       - match: \b(?i)(CLERIC_CAUSE_LIGHT_WOUNDS)\b
>       ...
> ```
> 
> I'm not quite sure yet what's the best way to support multiple games syntaxes, but for now it's probably best to keep the lists separate.

OK, done.

**Comment by burner1024** [comment]
Thank you, merged.

**Pull request merged**
