### PR TITLE
Added missing "\"

### PR DESCRIPTION
**Pull request by 4Luke4**

### CODE REVIEW

**Comment by burner1024** [comment]
there are some conflicts...

**Comment by 4Luke4** [comment]
> there are some conflicts...

Yeah, probably because I forgot to update my fork before committing.....

However, when I click on "Resolve conflicts", it keeps processing `weidu.completion.yml` (i.e., it never stops....) Do you have any suggestion?

**Comment by burner1024** [comment]
ctrl-f5?

**Comment by 4Luke4** [comment]
> ctrl-f5?
> Or you can pull upstream and resolve locally. It's probably choking on replaced dashes

Done.
Please tell me if I messed up something.....

**Comment by burner1024** [comment]
Seems that VScode just [doesn't support](https://github.com/Microsoft/language-server-protocol/issues/137) newlines in plain text doc.
I think to get it working, we'll need to write the corresponding doc in markdown and add support for this in MLS.

**Comment by burner1024** [comment]
OK, so competion item recognizes markdown natively.
But line endings should be marked with "**\n**", not just "**\**".
And the additional slash at the beginning of the next string is not necessary.

Captura de pantalla de 2019-06-13 00-39-02
Captura de pantalla de 2019-06-13 00-39-12

**Comment by burner1024** [comment]
only the trailing ones

**Comment by 4Luke4** [comment]
> only the trailing ones

Done.

**Comment by 4Luke4** [comment]
Moreover, how can I add `BEGIN`, `END`, `LAF` and `LPF` to Autocompletion?

**Comment by burner1024** [comment]
I thought you're comfortable enough with yaml structure already, what's the problem? (In any case, let's keep it separate.)

Also, you might want to take a look at [snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets) instead or in addition. They allow to insert larger, predefined text blolcks (such as LAF.. INT_VAR ... STR_VAR.. END), and the fill in the blanks easily.
Examples [here](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/master/snippets/fallout-ssl.json).

**Comment by burner1024** [comment]
And yaml is broken again. See the linter.

**Comment by 4Luke4** [comment]
> And yaml is broken again. See the linter.

VScode highlights nothing for me.... What's exactly the issue?

**Comment by burner1024** [comment]
Looks good now.

**Comment by 4Luke4** [comment]
@burner1024 

Forgot to make the release?

**Comment by burner1024** [comment]
No, just waiting to see if you send any more pulls.
Also, some updates for Fallout module are coming soon, I want to batch that.

**Comment by 4Luke4** [comment]
> No, just waiting to see if you send any more pulls.
> Also, some updates for Fallout module are coming soon, I want to batch that.

I see.
Well, I may add `INT_VAR`, `STR_VAR`, `RET`, `BEGIN` and `END` to the 'constants' section and try to write down some snippets to automate LAF/LPF invocations......

**Comment by burner1024** [comment]
Released it.

We now have a semi-automatic system to pull Fallout syntax changes. Would be awesome to implement something similar for WeiDU and IESDP.

**Comment by 4Luke4** [comment]
> Also, you might want to take a look at [snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets) instead or in addition. They allow to insert larger, predefined text blolcks (such as LAF.. INT_VAR ... STR_VAR.. END), and the fill in the blanks easily.
> Examples [here](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/master/snippets/fallout-ssl.json).

So, something like this
```
{
    "LAUNCH_ACTION_FUNCTION": {
        "prefix": "LAF",
        "body": [
          "${1|INT_VAR,STR_VAR,RET|}",
          "\t$0",
          "END"
        ],
        "description": "Launch an action function."
    }
}
```
?

**Comment by burner1024** [comment]
> So, something like this

Looks ok, but need to test to be sure.
You can launch the development version of the extension by pressing F5 in VScode.

**Comment by 4Luke4** [comment]
@burner1024 

Sorry for reviving this, but it seems that some `\n` are not functional (look at the attached screenshot).
Do you know why?
Missing  n

**Comment by burner1024** [comment]
I'm not sure, but I was able to get it to work using the the [other syntax](https://github.com/BGforgeNet/vscode-bgforge-mls/commit/6677685282228cf96c8c6248765b752d39e9306c) (`doc: |`):
Captura de pantalla de 2019-07-01 19-41-47



What concerns me more is that markdown is not displayed properly in completion:

Captura de pantalla de 2019-07-01 19-28-27
Was it always like that?

**Pull request merged**
