### PR TITLE
Autocompletion: WeiDU patch and macro functions

### PR DESCRIPTION
**Pull request by 4Luke4**
Added some missing patch and macro/action functions.

### CODE REVIEW

**Comment by burner1024** [comment]
Need to quote properly. This is broken yaml.

Captura de pantalla de 2019-06-11 14-33-43

**Comment by 4Luke4** [comment]
> Need to quote properly. This is broken yaml.

They need to be em dashes (–)?

**Comment by burner1024** [comment]
That'd maybe work, but it's easier to just quote the doc fully, so it's a single string:

Captura de pantalla de 2019-06-11 15-17-55

**Comment by 4Luke4** [comment]
@burner1024 

Is it OK now?

**Comment by burner1024** [comment]
No, there are still errors:

Captura de pantalla de 2019-06-11 16-31-10

Doesn't VScode highlight that for you?

On the other hand, adding single quotes as in `- INT_VAR 'special' to the new special parameter.` is not necessary.

**Comment by 4Luke4** [comment]
> On the other hand, adding single quotes as in `- INT_VAR 'special' to the new special parameter.` is not necessary.

I wanted to highlight the actual variable so that it properly distinguishes from the rest of the text...
Did you mean this is automatically done?

**Comment by burner1024** [comment]
No, it isn't, I just meant that it's not the cause of the errors. If you think that'd be helpful, it's just as well.

**Comment by 4Luke4** [comment]
> No, there are still errors:
> 
> Captura de pantalla de 2019-06-11 16-31-10
> 
> Doesn't VScode highlight that for you?

No, it doesn't.
Anyway, what's the problem now? Everything seems to be quoted properly.....

**Comment by burner1024** [comment]
Do you have yaml extension installed?

Double qoutes inside double quotes should be escaped.
Captura de pantalla de 2019-06-11 17-05-17. "same" breaks the string.

**Comment by 4Luke4** [comment]
> Do you have yaml extension installed?

Installed.

> Double qoutes inside double quotes should be escaped.

Done.

**Comment by burner1024** [comment]
That looks better. Did you make the dashes long after all, though?
Theoretically, it should be all utf8 with no problems, but still I prefer to keep it ascii, replacing stuff like "’" and "–" with proper single quotes and dashes.

Also, you shouldn't change *.tmLanguage.json files manually, these files are generated from corresponding *.tmLanguage.yml by a script. (Json is just too verbose to work with).

**Comment by 4Luke4** [comment]
> That looks better. Did you make the dashes long after all, though?
>
Only for the last functions I added - I didn't go back to edit the ones already there...

> Also, you shouldn't change *.tmLanguage.json files manually, these files are generated from corresponding *.tmLanguage.yml by a script. (Json is just too verbose to work with).
>
I see => reverted previous commit

**Comment by 4Luke4** [comment]
@burner1024 

If everything is OK now, feel free to merge...

**Comment by burner1024** [comment]
Thank you, it is merged and published.

**Comment by 4Luke4** [comment]
> Thank you, it is merged and published.

No Changelog?
Moreover, I'm gonna make another pull request to add some `\` (otherwise everything is on the same line...)

**Comment by burner1024** [comment]
oh yes, added now.

**Pull request merged**
