### PR TITLE
[WeiDU, .baf files]Added some useful identifiers to Syntax Highlighting – Part 2

### PR DESCRIPTION
**Pull request by 4Luke4**
So far:
```
areaflag.ids
areatype.ids
button.ids
classcat.ids
difflev.ids
modal.ids
scrlev.ids
seq.ids
time.ids
timeoday.ids
weather.ids
xequip.ids
statmod.ids
wprof.ids
dir.ids
boolean.ids
astyles.ids
invitem.ids
itemflag.ids
jourtype.ids
mflags.ids
music.ids
reaction.ids
shoutids.ids
happy.ids
```

Moreover:

- I decided to remove `(?i)` so that `BAF` identifiers don't (hopefully!) get confused with `SLB` triggers/targets.
- I added support for hexadecimal numbers in `D` and `BAF` files.

### CODE REVIEW

**Comment by burner1024** [comment]
That's a lot of additions, thank you. I'll take a look a bit later.

**Comment by 4Luke4** [comment]
Added the keywords `ELSE` and `THIS`.
Example:

`WRITE_LONG 0x18 (THIS | BIT6)`
```
ACTION_IF (value) BEGIN
  FAIL "some text"
END ELSE BEGIN
  WARN "some other text"
END
```

**Comment by burner1024** [comment]
Is that all for now or are you going to add anything else?

**Comment by 4Luke4** [comment]
> Is that all for now or are you going to add anything else?

That's all for now...

**Comment by burner1024** [comment]
OK, thank you. It's published now.

**Pull request merged**
